### ISSUE TITLE
Build claims to complete but no build directory exists.

### ISSUE THREAD

**Issue by KR0SIV** [DSheirer/jmbe#12]
After running the gradlew script I get the following output

```
C:\Users\KR0SIV\Desktop\jmbe-0.3.3b\jmbe-0.3.3b>gradlew.bat

 Configure project :
Your finished JMBE library is here: C:\Users\KR0SIV\Desktop\jmbe-0.3.3b\jmbe-0.3.3b\build/libs

 Task :help

Welcome to Gradle 4.4.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>


BUILD SUCCESSFUL in 1s
```

The problem is that build directory doesn't exist and no jar file was actually created.
I can compile it myself but it should be noted the script is claiming to have completed successfully when from what I can tell it created no .jar in the process.

**Comment by xscode** [comment]
It should be "gradlew.bat build" i think.

**Comment by matthias-he** [comment]
With the correct command 'gradlew.bat build' the same issue persists. Successful compilation/build message but no build directory or file anywhere.

**Comment by matthias-he** [comment]
Resolution after more work:
 
Copy/paste the unzipped folder "jmbe-0.3.3b" into YOUR Windows User directory, e.g. into C:\Users\Joe Sample  so that the resulting path is for example  C:\Users\Joe Sample\jmbe-0.3.3b .
  
-> Discovered rationale: the automated Gradlew tool download that the greadlew.bat file triggers will only go into this User directory. And the gradlew tool must have EVERYTHING together in this User directory. (Gradlew is NOT flexible to find the files to compile in other directories outside of the one it was downloaded into.)
 
Run the build script while in the correct directory: 

C:\Users\Joe Sample\jmbe-0.3.3b> gradlew.bat build
 
The compiled JMBE library will be located in a sub-folder named '\build\libs':
C:\Users\Joe Sample\jmbe-0.3.3b\jmbe\build\libs

**Comment by matthias-he** [comment]
Recommended edits in two files that worked fine, based on findings by other contributors:
 
\\jmbe-0.3.3b\build.gradle :  

Line 69   task Wrapper(type: Wrapper) {
Line 70       gradleVersion = '5.1.1'
Line 71   }
 
 
\\jmbe-0.3.3b\gradle\wrapper\gradle-wrapper.properties :
  
Line 5   distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-bin.zip

**Comment by mikerobertsn** [comment]
I have tried all these and still no luck, it says build successful, but files are found. Can i just download the .jar from somewhere?

**Comment by DSheirer** [comment]
Closing issue.
